### ISSUE TITLE
Some hints getting it to work on windows

### ISSUE THREAD

**Issue by raue** [oleschum/radar_scenes#1]
Just in case the documentation shall be extended by adding some installation hints:

When getting "*qt.qpa.plugin: Could not load the Qt platform plugin "windows" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.*" don't give up. Instead, you should try this:
1. set an additional environment variable pointing to your anaconda plugins directory
(e.g. *set QT_PLUGIN_PATH=c:\util\anaconda3\Library\plugins*)
2. copy the right dlls into the directory above - hint taken from [LINK](https://stackoverflow.com/questions/41994485/how-to-fix-could-not-find-or-load-the-qt-platform-plugin-windows-while-using-m):
 copy the following files ... 
_\Anaconda3\Lib\site-packages\PySide2\plugins\platforms\qminimal.dll
\Anaconda3\Lib\site-packages\PySide2\plugins\platforms\qoffscreen.dll
\Anaconda3\Lib\site-packages\PySide2\plugins\platforms\qwindows.dll_
to:
_\Anaconda3\Library\plugins\platforms_

**Comment by oleschum** [comment]
Thanks for the input! 
I think this is not directly related to my code but rather a general Qt/Windows/Anacoda thing, right? So I guess there is not much I can change on the code itself.

But if you want to, you can add this info to the Readme.md and create a pull request. This might be helpful for other Windows users as well.
