### ISSUE TITLE
Could I use the vr_compensated of target to calculate the velocity of target !?

### ISSUE THREAD

**Issue by joeking11829** [oleschum/radar_scenes#17]
Hi @oleschum ,

As the title metions,
Could I use the vr_compensated to recover the velocity !?
As I known, Vr (radial velocity ) = V ( velocity ) dot DirectionUnitVector ( radial direction )
and I can recover the DirectionUnitVector by calculate the norm of ( Radar Point (XYZ) - Radar Origin )
So I can calculate the V (velocity).

When the sensor moving, Vr = ( V_sensor ( sensor velocity ) dot DirectionUnitVector ) - ( V ( velocity ) dot DirectionUnitVector )
If I can get V_sensor then I still can calculate the V (velocity).

Am I correct !?

Thanks !!

**Comment by oleschum** [comment]
With the measurement of a single detection you cannot calculate the complete velocity vector of an object.
