### ISSUE TITLE
Some questions about the radial direction of "vr" and "vr_compensated" ...

### ISSUE THREAD

**Issue by joeking11829** [oleschum/radar_scenes#18]
Hi @oleschum 

Thanks for your quick reply on last issue.

Based on my knowledge, 
the radial direction of "vr" and "vr_compensated" is the same,
no matter the object is moving or not.

The radial direction which is a vector point from radar origin to radar point,
because "RadarScenes" only provide the scalar of radial velocity ( vr and vr_compensated ),
when draw the vector of "vr" or "vr_compensated" is use the code below ( reference from view.py) :
```
angles = radar_data["azimuth_sc"] + sensor_yaw
vrx_comp = radar_data["vr_compensated"] * np.cos(angles)
vry_comp = radar_data["vr_compensated"] * np.sin(angles)

# when drawing "vr"
vrx = radar_data["vr"] * np.cos(angles)
vry = radar_data["vr"] * np.sin(angles)
```
The vector of radial velocity always point from radar origin to radar point.

But I found that nuScenes is not the same.
The radial velocity of nuScenes is given by vx and vy,
when the object is moving, the vector does not point from radar origin to radar point.

It seems to me thatThe define of radial velocity is different between RadarScenes and nuScenes.

Any Ideas !?

Thanks !!

**Comment by MaxPRon** [comment]
Is there any progess on that point ? 

I'm also a little bit confused about what the exact defintion of vr_compensated is. 

In which way has the range rate been compensated ?

**Comment by oleschum** [comment]
To the original question: I don't know exactly what NuScenes does do come up with vx and vy. Maybe this is some estimated Cartesian velocity (so an estimate of both the radial and tangential velocity component).

@MaxPRon  vr_compensated has the same direction (up to a possible sign flip) as vr. But vr_compensated is the radial velocity of the target with compensated ego-motion of the radar sensor. They are the same only if the ego-vehicle is stationary.

**Comment by MaxPRon** [comment]
@oleschum  Thanks a lot for the answer :)

Just for confirmation: vr_compensated is the range rate (vr) in the sensor-frame with the addition of the ego-motion that has been projected into the "range rate direction" in the sensor frame.

Is this correct ?

**Comment by oleschum** [comment]
Yes, that is correct.

**Comment by MaxPRon** [comment]
Alright, thanks a lot!
