### ISSUE TITLE
is Radial Velocity is given in the radar data

### ISSUE THREAD

**Issue by v-shetty** [oleschum/radar_scenes#2]
Thank you for the entire dataset.

    X = np.zeros((len(radar_data), 4))  # construct feature vector
    X[:, 0] = radar_data["x_cc"]
    X[:, 1] = radar_data["y_cc"]
    X[:, 2] = radar_data["vr_compensated"]
    X[:, 3] = radar_data["rcs"]

in the above code, we get X and Y and also doppler velocity which is compensated with ego velocity. 
but ,
is the doppler velocity without ego compensation is avaialbe?

**Comment by oleschum** [comment]
Hi,
yes, the Doppler velocity without ego-motion compensation is available in the column "vr".
See also here: https://radar-scenes.com/dataset/structure/#radar_datah5
