### ISSUE TITLE
May I ask how you label semantically segmented image data into radar data categories?

### ISSUE THREAD

**Issue by YufanHuang** [oleschum/radar_scenes#21]
I read your code and used the tool . Now I want to label my own radar data follow your proposed method.May I ask how you label semantically segmented image data into radar data categories?

**Comment by oleschum** [comment]
The original labeling of the data was done with camera images that were not painted over. The semantic segmentation of the camera images was only done later in order to comply with data privacy regulations.

**Comment by YufanHuang** [comment]
thank you for your reply. Do you project the image into a bird's-eye view, or project the radar point cloud into the image for annotation?

**Comment by oleschum** [comment]
We did not project the data. Annotation was done manually in the birds eye view of the radar detections. Camera was used as reference.
