### ISSUE TITLE
Resampling issue

### ISSUE THREAD

**Issue by akinsevimli** [oleschum/radar_scenes#3]
Hello, 

In your "Semantic Segmentation on Radar Point Clouds" paper, it says "if less than 3072 reflections were measured, one reflectionwas re-sampled the required amount of times." .

How did you resampled RCS and Velocity values? What was the criteria?

Thank you.

**Comment by oleschum** [comment]
Re-sampling just means that one detection is repeated the required number of times. No new values are created. Since the NN is invariant to adding same points, this does not change the output.
