### ISSUE TITLE
Raw camera images

### ISSUE THREAD

**Issue by pjckoch** [oleschum/radar_scenes#4]
Hi @oleschum ,

thanks a lot for sharing this dataset.

I noticed that what is given as camera already contains embedded instance annotations. I was wondering if it is possible to provide the raw camera images and the instances separately. That would be very helpful.

Thank you very much in advance.

Best regards,
Patrick

**Comment by oleschum** [comment]
Hi @pjckoch ,
your observation is correct: only the re-painted images with instance segmentation are available in the data set.
This was done on purpose, since sharing the raw-images would violate the GDPR as we would share personal information (license plates, faces, etc.). 

So in short: No, the raw images will not be available.
Sorry about that!

**Comment by pjckoch** [comment]
Hi @oleschum,

thank you for getting back to me so quickly! Ok, I understand. However, I think there would be a lot of use-cases in which you want to incorporate information from the image space, too.

Have you considered blurring out faces and license plates as is done in Cityscapes (see screenshot)?

Thank you and best regards,

Patrick

![MicrosoftTeams-image](https://user-images.githubusercontent.com/38760750/121230260-5234c280-c88f-11eb-9cf6-02d6371bf990.png)

**Comment by oleschum** [comment]
Hi @pjckoch,
I understand that there are many use cases in which additional camera data is of help - the whole field of sensor data fusion opens up with this extra information. So of course, we considered including the data and also considered the different anonymization options. 
However, the legal perspective for our data set is different than for cityscapes (the devil is in the details here) and hence blurring of faces is not sufficient. Thats why we went with the instance segmentation appraoch and will stick with it.

**Comment by pjckoch** [comment]
Hi @oleschum ,

ok, that's a pity, but I understand. Thank you very much for the prompt and detailed answers!

Best regards
Patrick
