### ISSUE TITLE
Where Can we find the calibration matrix to map camera into radar FOV?

### ISSUE THREAD

**Issue by BaiLiping** [oleschum/radar_scenes#6]

**Comment by oleschum** [comment]
I am sorry, but there is none.

**Comment by BaiLiping** [comment]
so how do you transfer the segmentation done with camera into radar data?

**Comment by BaiLiping** [comment]
did you guys to the camera labelling and radar labelling separately? so there is no corresponding relationship whatsoever?

**Comment by BaiLiping** [comment]
To ensure high quality annotations and not have to rely on instructed road users, the introduced  data  set  uses  only  manually  labeled  data  created by human experts

**Comment by BaiLiping** [comment]
so the labelling in camera view is just to obfuscate the identity?
