### ISSUE TITLE
About the vehicle’s motion state information

### ISSUE THREAD

**Issue by wzan0001** [oleschum/radar_scenes#7]
Hi, in your paper the vehicle’s motion state (i.e. position, orientation, velocity, and yaw rate) is recorded. I'd like to know how this information is obtained, by GPS or RTK or IMU? how accurate is the ego-position information?

**Comment by oleschum** [comment]
The odometry information is obtained from on-board sensors as well as from a DGPS system. I do not have any KPIs at hand which give further information about the accuracy of the odometry.
